//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoralesFiFthCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string description { get; set; }
        public Nullable<int> price { get; set; }
        public int UserId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public byte[] ProductImg { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
